// <auto-generated />
namespace IdentityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GetBookMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetBookMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201812241943016_GetBookMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
